language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
script: npm test && npm run build
deploy:
  provider: pages
  repo: gtbuchanan/gtbuchanan.github.io
  target-branch: main
  github-token: $GITHUB_TOKEN
  keep-history: true
  skip-cleanup: true
  local-dir: build
  on:
    branch: main
